// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFSgWsxUTrBz2K5h6WTi_mwSjoEpo947c',
    appId: '1:846944364575:android:f41df84158160110498d2a',
    messagingSenderId: '846944364575',
    projectId: 'novyn-chat-app',
    storageBucket: 'novyn-chat-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFzdye4i2Wk_PxhoXuGmJDBoamzAlaTbk',
    appId: '1:846944364575:ios:628ab7f4e42bc8db498d2a',
    messagingSenderId: '846944364575',
    projectId: 'novyn-chat-app',
    storageBucket: 'novyn-chat-app.firebasestorage.app',
    androidClientId: '846944364575-a1u9n1fo789a61f4370loejpjltgp6oo.apps.googleusercontent.com',
    iosClientId: '846944364575-oafk0h52oj0t3qb66472l2i3hb152eoi.apps.googleusercontent.com',
    iosBundleId: 'com.example.novyn',
  );

}